// Mocks generated by Mockito 5.4.6 from annotations
// in sunnova_app/test/features/home/data/repositories/home_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sunnova_app/features/home/data/datasources/home_local_data_source.dart'
    as _i3;
import 'package:sunnova_app/features/home/data/models/course_module_model.dart'
    as _i5;
import 'package:sunnova_app/features/home/data/models/user_game_stats_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserGameStatsModel_0 extends _i1.SmartFake
    implements _i2.UserGameStatsModel {
  _FakeUserGameStatsModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeLocalDataSource extends _i1.Mock
    implements _i3.HomeLocalDataSource {
  MockHomeLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserGameStatsModel> getUserGameStats(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserGameStats, [userId]),
            returnValue: _i4.Future<_i2.UserGameStatsModel>.value(
              _FakeUserGameStatsModel_0(
                this,
                Invocation.method(#getUserGameStats, [userId]),
              ),
            ),
          )
          as _i4.Future<_i2.UserGameStatsModel>);

  @override
  _i4.Future<List<_i5.CourseModuleModel>> getCourseModules() =>
      (super.noSuchMethod(
            Invocation.method(#getCourseModules, []),
            returnValue: _i4.Future<List<_i5.CourseModuleModel>>.value(
              <_i5.CourseModuleModel>[],
            ),
          )
          as _i4.Future<List<_i5.CourseModuleModel>>);

  @override
  _i4.Future<void> saveUserGameStats(_i2.UserGameStatsModel? stats) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserGameStats, [stats]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveCourseModules(List<_i5.CourseModuleModel>? modules) =>
      (super.noSuchMethod(
            Invocation.method(#saveCourseModules, [modules]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
