// Mocks generated by Mockito 5.4.6 from annotations
// in sunnova_app/test/features/auth/data/datasources/auth_local_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;
import 'package:sunnova_app/core/db/database_helper.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i3.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i4.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i4.Future<_i2.Database>);

  @override
  _i4.Future<int> insertUser(Map<String, dynamic>? user) =>
      (super.noSuchMethod(
            Invocation.method(#insertUser, [user]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<Map<String, dynamic>?> getUser(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [uid]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<Map<String, dynamic>?> getUserByEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByEmail, [email]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<int> updateUser(Map<String, dynamic>? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteUser(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [uid]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> insertBadge(Map<String, dynamic>? badge) =>
      (super.noSuchMethod(
            Invocation.method(#insertBadge, [badge]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAllBadges() =>
      (super.noSuchMethod(
            Invocation.method(#getAllBadges, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<int> insertCourseModule(Map<String, dynamic>? module) =>
      (super.noSuchMethod(
            Invocation.method(#insertCourseModule, [module]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<Map<String, dynamic>?> getCourseModule(String? moduleId) =>
      (super.noSuchMethod(
            Invocation.method(#getCourseModule, [moduleId]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAllCourseModules() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCourseModules, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<int> insertLessonUnit(Map<String, dynamic>? lesson) =>
      (super.noSuchMethod(
            Invocation.method(#insertLessonUnit, [lesson]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getLessonUnitsByModuleId(
    String? moduleId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLessonUnitsByModuleId, [moduleId, userId]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>?> getLessonUnit(String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#getLessonUnit, [lessonId]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<int> insertAssessmentQuestion(Map<String, dynamic>? question) =>
      (super.noSuchMethod(
            Invocation.method(#insertAssessmentQuestion, [question]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAssessmentQuestionsByLessonId(
    String? lessonId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAssessmentQuestionsByLessonId, [lessonId]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<int> insertUserAchievement(Map<String, dynamic>? achievement) =>
      (super.noSuchMethod(
            Invocation.method(#insertUserAchievement, [achievement]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getUserAchievements(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserAchievements, [userId]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<int> insertUserGameStats(Map<String, dynamic>? stats) =>
      (super.noSuchMethod(
            Invocation.method(#insertUserGameStats, [stats]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<Map<String, dynamic>?> getUserGameStats(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserGameStats, [userId]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<int> updateUserGameStats(Map<String, dynamic>? stats) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserGameStats, [stats]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> insertUserLessonProgress(Map<String, dynamic>? progress) =>
      (super.noSuchMethod(
            Invocation.method(#insertUserLessonProgress, [progress]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> updateUserLessonProgress(Map<String, dynamic>? progress) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserLessonProgress, [progress]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<Map<String, dynamic>?> getUserLessonProgress(
    String? userId,
    String? lessonId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserLessonProgress, [userId, lessonId]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<int> insertUserAnswerLog(Map<String, dynamic>? answerLog) =>
      (super.noSuchMethod(
            Invocation.method(#insertUserAnswerLog, [answerLog]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getLeaderboardRanks() =>
      (super.noSuchMethod(
            Invocation.method(#getLeaderboardRanks, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);
}
