// Mocks generated by Mockito 5.4.6 from annotations
// in sunnova_app/test/features/course/presentation/notifiers/course_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sunnova_app/core/error/failures.dart' as _i6;
import 'package:sunnova_app/features/course/domain/entities/lesson_unit_entity.dart'
    as _i9;
import 'package:sunnova_app/features/course/domain/entities/user_lesson_progress_entity.dart'
    as _i11;
import 'package:sunnova_app/features/course/domain/repositories/course_repository.dart'
    as _i2;
import 'package:sunnova_app/features/course/domain/usecases/get_course_detail.dart'
    as _i4;
import 'package:sunnova_app/features/course/domain/usecases/get_lesson_units.dart'
    as _i8;
import 'package:sunnova_app/features/course/domain/usecases/get_user_lesson_progress.dart'
    as _i10;
import 'package:sunnova_app/features/home/domain/entities/course_module_entity.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCourseRepository_0 extends _i1.SmartFake
    implements _i2.CourseRepository {
  _FakeCourseRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetCourseDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCourseDetail extends _i1.Mock implements _i4.GetCourseDetail {
  MockGetCourseDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CourseRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCourseRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CourseRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.CourseModuleEntity>> call(
    _i4.GetCourseDetailParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i5.Future<
                  _i3.Either<_i6.Failure, _i7.CourseModuleEntity>
                >.value(
                  _FakeEither_1<_i6.Failure, _i7.CourseModuleEntity>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.CourseModuleEntity>>);
}

/// A class which mocks [GetLessonUnits].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLessonUnits extends _i1.Mock implements _i8.GetLessonUnits {
  MockGetLessonUnits() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CourseRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCourseRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CourseRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i9.LessonUnitEntity>>> call(
    _i8.GetLessonUnitsParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i5.Future<
                  _i3.Either<_i6.Failure, List<_i9.LessonUnitEntity>>
                >.value(
                  _FakeEither_1<_i6.Failure, List<_i9.LessonUnitEntity>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, List<_i9.LessonUnitEntity>>>);
}

/// A class which mocks [GetUserLessonProgress].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserLessonProgress extends _i1.Mock
    implements _i10.GetUserLessonProgress {
  MockGetUserLessonProgress() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CourseRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCourseRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CourseRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i11.UserLessonProgressEntity>> call(
    _i10.GetUserLessonProgressParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i5.Future<
                  _i3.Either<_i6.Failure, _i11.UserLessonProgressEntity>
                >.value(
                  _FakeEither_1<_i6.Failure, _i11.UserLessonProgressEntity>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<
            _i3.Either<_i6.Failure, _i11.UserLessonProgressEntity>
          >);
}
