// Mocks generated by Mockito 5.4.6 from annotations
// in sunnova_app/test/features/course/data/repositories/course_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sunnova_app/features/course/data/datasources/course_local_data_source.dart'
    as _i5;
import 'package:sunnova_app/features/course/data/models/lesson_unit_model.dart'
    as _i4;
import 'package:sunnova_app/features/course/data/models/user_lesson_progress_model.dart'
    as _i3;
import 'package:sunnova_app/features/home/data/models/course_module_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCourseModuleModel_0 extends _i1.SmartFake
    implements _i2.CourseModuleModel {
  _FakeCourseModuleModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserLessonProgressModel_1 extends _i1.SmartFake
    implements _i3.UserLessonProgressModel {
  _FakeUserLessonProgressModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLessonUnitModel_2 extends _i1.SmartFake
    implements _i4.LessonUnitModel {
  _FakeLessonUnitModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CourseLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCourseLocalDataSource extends _i1.Mock
    implements _i5.CourseLocalDataSource {
  MockCourseLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.CourseModuleModel> getCourseDetail(String? moduleId) =>
      (super.noSuchMethod(
            Invocation.method(#getCourseDetail, [moduleId]),
            returnValue: _i6.Future<_i2.CourseModuleModel>.value(
              _FakeCourseModuleModel_0(
                this,
                Invocation.method(#getCourseDetail, [moduleId]),
              ),
            ),
          )
          as _i6.Future<_i2.CourseModuleModel>);

  @override
  _i6.Future<List<_i4.LessonUnitModel>> getLessonUnits(
    String? moduleId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLessonUnits, [moduleId, userId]),
            returnValue: _i6.Future<List<_i4.LessonUnitModel>>.value(
              <_i4.LessonUnitModel>[],
            ),
          )
          as _i6.Future<List<_i4.LessonUnitModel>>);

  @override
  _i6.Future<_i3.UserLessonProgressModel> getUserLessonProgress(
    String? userId,
    String? lessonId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserLessonProgress, [userId, lessonId]),
            returnValue: _i6.Future<_i3.UserLessonProgressModel>.value(
              _FakeUserLessonProgressModel_1(
                this,
                Invocation.method(#getUserLessonProgress, [userId, lessonId]),
              ),
            ),
          )
          as _i6.Future<_i3.UserLessonProgressModel>);

  @override
  _i6.Future<void> markLessonAsCompleted(String? userId, String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#markLessonAsCompleted, [userId, lessonId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.LessonUnitModel> getLessonContent(String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#getLessonContent, [lessonId]),
            returnValue: _i6.Future<_i4.LessonUnitModel>.value(
              _FakeLessonUnitModel_2(
                this,
                Invocation.method(#getLessonContent, [lessonId]),
              ),
            ),
          )
          as _i6.Future<_i4.LessonUnitModel>);
}
