// Mocks generated by Mockito 5.4.6 from annotations
// in sunnova_app/test/features/course/domain/usecases/course_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sunnova_app/core/error/failures.dart' as _i5;
import 'package:sunnova_app/features/course/domain/entities/lesson_unit_entity.dart'
    as _i7;
import 'package:sunnova_app/features/course/domain/entities/user_lesson_progress_entity.dart'
    as _i8;
import 'package:sunnova_app/features/course/domain/repositories/course_repository.dart'
    as _i3;
import 'package:sunnova_app/features/home/domain/entities/course_module_entity.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CourseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCourseRepository extends _i1.Mock implements _i3.CourseRepository {
  MockCourseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.CourseModuleEntity>> getCourseDetail(
    String? moduleId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCourseDetail, [moduleId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.CourseModuleEntity>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.CourseModuleEntity>(
                    this,
                    Invocation.method(#getCourseDetail, [moduleId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.CourseModuleEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.LessonUnitEntity>>>
  getLessonUnits(String? moduleId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getLessonUnits, [moduleId, userId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i7.LessonUnitEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i7.LessonUnitEntity>>(
                    this,
                    Invocation.method(#getLessonUnits, [moduleId, userId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i7.LessonUnitEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.UserLessonProgressEntity>>
  getUserLessonProgress(String? userId, String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserLessonProgress, [userId, lessonId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i8.UserLessonProgressEntity>
                >.value(
                  _FakeEither_0<_i5.Failure, _i8.UserLessonProgressEntity>(
                    this,
                    Invocation.method(#getUserLessonProgress, [
                      userId,
                      lessonId,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.UserLessonProgressEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> markLessonAsCompleted(
    String? userId,
    String? lessonId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markLessonAsCompleted, [userId, lessonId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#markLessonAsCompleted, [userId, lessonId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.LessonUnitEntity>> getLessonContent(
    String? lessonId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLessonContent, [lessonId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.LessonUnitEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i7.LessonUnitEntity>(
                    this,
                    Invocation.method(#getLessonContent, [lessonId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.LessonUnitEntity>>);
}
